In [1]:
import sqlite3

In [2]:
conn = sqlite3.connect('projetofinal.db')

In [3]:
import requests
import pandas as pd

url = "https://brasilapi.com.br/api/banks/v1"
req = requests.get(url)
data = req.json()

# Renomear colunas
df = pd.DataFrame(data)
df.rename(columns={'ispb': 'ISPB', 'name': 'Nome', 'code': 'Código', 'fullName': 'Nome Banco'}, inplace=True)#renomer as colunas nome coluna:novo nome

# Tratar  variáveis
df['Código'] = df['Código'].astype('Int64')

# missing
df.fillna({'Código': 0, 'Nome Banco': 'Sem nome'}, inplace=True)  #substituir o NA dos codigos por zeros, tratar nome de bancos sem valor

# Tratamento de  strings
df['Nome'] = df['Nome'].str.upper()  #faz a linha toda nome ficar maiscula
df['Nome Banco'] = df['Nome Banco'].str.title() #faz a primeira linha do nome banco ser maiscula

df.to_sql('df', conn, if_exists='replace', index=False)

df.head(50)

,ISPB,Nome,Código,Nome Banco
0,00000000,BCO DO BRASIL S.A.,1,Banco Do Brasil S.A.
1,00000208,BRB - BCO DE BRASILIA S.A.,70,Brb - Banco De Brasilia S.A.
2,00038121,SELIC,0,Banco Central Do Brasil - Selic
3,00038166,BACEN,0,Banco Central Do Brasil
4,00122327,SANTINVEST S.A. - CFI,539,"Santinvest S.A. - Credito, Financiamento E Inv..."
5,00204963,CCR SEARA,430,Cooperativa De Credito Rural Seara - Crediseara
6,00250699,AGK CC S.A.,272,Agk Corretora De Cambio S.A.
7,00315557,CONF NAC COOP CENTRAIS UNICRED,136,Confederação Nacional Das Cooperativas Centrai...
8,00329598,ÍNDIGO INVESTIMENTOS DTVM LTDA.,407,Índigo Investimentos Distribuidora De Títulos ...
9,00360305,CAIXA ECONOMICA FEDERAL,104,Caixa Economica Federal
10,00394460,STN,0,Secretaria Do Tesouro Nacional - Stn
11,00416968,BANCO INTER,77,Banco Inter S.A.
12,00460065,COLUNA S.A. DTVM,423,Coluna S/A Distribuidora De Titulos E Valores ...
13,00517645,BCO RIBEIRAO PRETO S.A.,741,Banco Ribeirao Preto S.A.
14,00556603,BANCO BARI S.A.,330,Banco Bari De Investimentos E Financiamentos S.A.
15,00558456,BCO CETELEM S.A.,739,Banco Cetelem S.A.
16,00714671,EWALLY IP S.A.,534,Ewally Instituição De Pagamento S.A.
17,00795423,BANCO SEMEAR,743,Banco Semear S.A.
18,00806535,PLANNER CV S.A.,100,Planner Corretora De Valores S.A.
19,00954288,FDO GARANTIDOR CRÉDITOS,541,Fundo Garantidor De Creditos - Fgc
20,00997185,BCO B3 S.A.,96,Banco B3 S.A.
21,01023570,BCO RABOBANK INTL BRASIL S.A.,747,Banco Rabobank International Brasil S.A.
22,01027058,CIELO IP S.A.,362,Cielo S.A. - Instituição De Pagamento
23,01073966,CCR DE ABELARDO LUZ,322,Cooperativa De Crédito Rural De Abelardo Luz -...
24,01181521,BCO COOPERATIVO SICREDI S.A.,748,Banco Cooperativo Sicredi S.A.
25,01330387,CREHNOR LARANJEIRAS,350,Cooperativa De Crédito Rural De Pequenos Agric...
26,01522368,BCO BNP PARIBAS BRASIL S A,752,Banco Bnp Paribas Brasil S.A.
27,01658426,CECM COOPERFORTE,379,Cooperforte - Cooperativa De Economia E Crédit...
28,01701201,KIRTON BANK,399,Kirton Bank S.A. - Banco Múltiplo
29,01852137,BCO BRASILEIRO DE CRÉDITO S.A.,378,Banco Brasileiro De Crédito Sociedade Anônima
30,01858774,BCO BV S.A.,413,Banco Bv S.A.
31,02038232,BANCO SICOOB S.A.,756,Banco Cooperativo Sicoob S.A. - Banco Sicoob
32,02276653,TRINUS CAPITAL DTVM,360,Trinus Capital Distribuidora De Títulos E Valo...
33,02318507,BCO KEB HANA DO BRASIL S.A.,757,Banco Keb Hana Do Brasil S.A.
34,02332886,XP INVESTIMENTOS CCTVM S/A,102,"Xp Investimentos Corretora De Câmbio,Títulos E..."
35,02398976,SISPRIME DO BRASIL - COOP,84,Sisprime Do Brasil - Cooperativa De Crédito
36,02685483,CM CAPITAL MARKETS CCTVM LTDA,180,"Cm Capital Markets Corretora De Câmbio, Título..."
37,02801938,BCO MORGAN STANLEY S.A.,66,Banco Morgan Stanley S.A.
38,02819125,UBS BRASIL CCTVM S.A.,15,"Ubs Brasil Corretora De Câmbio, Títulos E Valo..."
39,02992317,TREVISO CC S.A.,143,Treviso Corretora De Câmbio S.A.
40,02992335,CIP SA SILOC,0,Cip S.A
41,03012230,HIPERCARD BM S.A.,62,Hipercard Banco Múltiplo S.A.
42,03017677,BCO. J.SAFRA S.A.,74,Banco J. Safra S.A.
43,03046391,UNIPRIME COOPCENTRAL LTDA.,99,Uniprime Central Nacional - Central Nacional D...
44,03215790,BCO TOYOTA DO BRASIL S.A.,387,Banco Toyota Do Brasil S.A.
45,03311443,PARATI - CFI S.A.,326,"Parati - Credito, Financiamento E Investimento..."
46,03323840,BCO ALFA S.A.,25,Banco Alfa S.A.
47,03532415,BCO ABN AMRO S.A.,75,Banco Abn Amro S.A.
48,03609817,BCO CARGILL S.A.,40,Banco Cargill S.A.
49,03751794,TERRA INVESTIMENTOS DTVM,307,Terra Investimentos Distribuidora De Títulos E...

In [4]:
import requests
import schedule
import time
import pandas as pd

url = "https://brasilapi.com.br/api/cptec/v1/cidade"

req = requests.get(url)

##req.status_code
##req.json()

data = req.json()


df2 = pd.DataFrame(data)
df2.rename(columns={'nome': 'Cidade','id':'Código', 'estado': 'UF'}, inplace=True)#renomer as colunas nome coluna:novo nome

df2.to_sql('df2', conn, if_exists='replace', index=False)
df2.head(60)

                       Cidade  Código  UF
0                São Benedito    4750  CE
1   São Benedito do Rio Preto    4751  MA
2         São Benedito do Sul    4752  PE
3                   São Bento    4753  MA
4                   São Bento    4754  PB
5             São Bento Abade    4755  MG
6         São Bento de Pombal    4756  PB
7          São Bento do Norte    4757  RN
8        São Bento do Sapucaí    4758  SP
9            São Bento do Sul    4759  SC
10     São Bento do Tocantins    4760  TO
11        São Bento do Trairi    4761  RN
12           São Bento do Una    4762  PE
13             São Bernardino    4763  SC
14               São Bernardo    4764  MA
15      São Bernardo do Campo    4765  SP
16              São Bonifácio    4766  SC
17                  São Borja    4767  RS
18                   São Brás    4768  AL
19         São Brás do Suaçuí    4769  MG
20          São Braz do Piauí    4770  PI
21    São Caetano de Odivelas    4771  PA
22         São Caetano do Sul    4772  SP
23                São Caitano    4773  PE
24                 São Carlos    4774  SP
25                 São Carlos    4775  SC
26         São Carlos do Ivaí    4776  PR
27              São Cristóvão    4777  SE
28       São Cristovão do Sul    4778  SC
29              São Desidério    4779  BA
30               São Domingos    4780  SE
31               São Domingos    4781  BA
32               São Domingos    4782  GO
33               São Domingos    4783  SC
34     São Domingos das Dores    4784  MG
35     São Domingos de Pombal    4785  PB
36   São Domingos do Araguaia    4786  PA
37    São Domingos do Azeitão    4787  MA
38      São Domingos do Capim    4788  PA
39     São Domingos do Cariri    4789  PB
40   São Domingos do Maranhão    4790  MA
41      São Domingos do Norte    4791  ES
42      São Domingos do Prata    4792  MG
43        São Domingos do Sul    4793  RS
44                 São Felipe    4794  BA
45          São Felipe dOeste    4795  RO
46                  São Félix    4796  BA
47        São Félix de Balsas    4797  MA
48         São Félix de Minas    4798  MG
49      São Félix do Araguaia    4799  MT
50        São Félix do Coribe    4800  BA
51         São Félix do Piauí    4801  PI
52     São Félix do Tocantins    4802  TO
53         São Félix do Xingu    4803  PA
54               São Fernando    4804  RN
55                São Fidélis    4805  RJ
56              São Francisco    4806  PB
57              São Francisco    4807  SE
58              São Francisco    4808  MG
59              São Francisco    4809  SP

In [5]:
import requests
import pandas as pd

url = "https://brasilapi.com.br/api/ibge/uf/v1"
req = requests.get(url)
data = req.json()

df3 = pd.DataFrame(data)

df3['regiao_id'] = df3['regiao'].apply(lambda id: id['id'])
df3['regiao_sigla'] = df3['regiao'].apply(lambda sigla: sigla['sigla'])
df3['regiao_nome'] = df3['regiao'].apply(lambda nome: nome['nome'])

# Dropar a coluna 'regiao' original
df3.drop(columns=['regiao'], inplace=True)
df3.rename(columns={'id': 'Código','sigla':'UF', 'nome': 'Estado'}, inplace=True)#renomer as colunas nome coluna:novo nome

df3.to_sql('df3', conn, if_exists='replace', index=False)
df3.head(27)

    Código  UF               Estado  regiao_id regiao_sigla   regiao_nome
0       11  RO             Rondônia          1            N         Norte
1       12  AC                 Acre          1            N         Norte
2       13  AM             Amazonas          1            N         Norte
3       14  RR              Roraima          1            N         Norte
4       15  PA                 Pará          1            N         Norte
5       16  AP                Amapá          1            N         Norte
6       17  TO            Tocantins          1            N         Norte
7       21  MA             Maranhão          2           NE      Nordeste
8       22  PI                Piauí          2           NE      Nordeste
9       23  CE                Ceará          2           NE      Nordeste
10      24  RN  Rio Grande do Norte          2           NE      Nordeste
11      25  PB              Paraíba          2           NE      Nordeste
12      26  PE           Pernambuco          2           NE      Nordeste
13      27  AL              Alagoas          2           NE      Nordeste
14      28  SE              Sergipe          2           NE      Nordeste
15      29  BA                Bahia          2           NE      Nordeste
16      31  MG         Minas Gerais          3           SE       Sudeste
17      32  ES       Espírito Santo          3           SE       Sudeste
18      33  RJ       Rio de Janeiro          3           SE       Sudeste
19      35  SP            São Paulo          3           SE       Sudeste
20      41  PR               Paraná          4            S           Sul
21      42  SC       Santa Catarina          4            S           Sul
22      43  RS    Rio Grande do Sul          4            S           Sul
23      50  MS   Mato Grosso do Sul          5           CO  Centro-Oeste
24      51  MT          Mato Grosso          5           CO  Centro-Oeste
25      52  GO                Goiás          5           CO  Centro-Oeste
26      53  DF     Distrito Federal          5           CO  Centro-Oeste

In [6]:
conn.close()

Alerta de erro

In [6]:
from datetime import datetime
from plyer import notification

def alerta(erro):
    '''
        Alerta de falha de carregamento de base de dados
    '''
    now = str(datetime.now())

    notification.notify(
            title= 'Aviso de erro',
            message= f'Falha no carregamento da base de dados',
            app_name='Alerta',
            timeout=10
        )

alerta('erro')